development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  database: itinarite_dev_new
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  database: itinarite_dev_new
  host: localhost