development:
  server: "http://localhost:9292/faye"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day

production:
  server: "http://private-hub-server.herokuapp.com/faye"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day