development:
  server: "http://localhost:9292/faye"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day

production:
  server: "http://52.15.83.199:9292/faye"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day